macro(system_info)
    message("=========SYSTEM INFO========")
    if(${WIN32})
        message("Running on WINDOWS")
    elseif(LINUX)
        message("Running on LINUX")
    endif()


    if(MSVC)
        message("Using MSVC")
        message("MSVS Version: ${MSVC_VERSION}")
    message("MSVS Version toolset: ${MSVC_TOOLSET_VERSION}")
    endif()

    message("Compiler flags: ${CMAKE_CXX_FLAGS}")
    message("Compiler debug flags: ${CMAKE_CXX_FLAGS_DEBUG}")
    message("Config types: ${CMAKE_CONFIGURATION_TYPES}")
    message("=============================================")
endmacro(system_info)

function(setup_precompiled_headers TARGET PCH_SOURCE PCH_HEADER SOURCE_FILES)
    if(MSVC)
        get_filename_component(PCH_HEADER_NAME ${PCH_HEADER} NAME)
        target_sources(${TARGET} PRIVATE ${PCH_HEADER} ${PCH_SOURCE})
        set_source_files_properties(${PCH_SOURCE} PROPERTIES COMPILE_FLAGS "/Yc${PCH_HEADER_NAME}")

        foreach(SOURCE_FILE ${SOURCE_FILES})
            if(${SOURCE_FILE} MATCHES "\\.cpp$" AND NOT ${SOURCE_FILE} STREQUAL ${PCH_SOURCE})
                set_source_files_properties(${SOURCE_FILE} PROPERTIES COMPILE_FLAGS "/Yu${PCH_HEADER_NAME}")
            endif()
        endforeach()
        target_compile_options(${TARGET} PRIVATE "/FI${PCH_HEADER_NAME}")
    endif()
endfunction()

macro(create_ide_folders SOURCE_FILES)
    foreach(SOURCE IN LISTS ${SOURCE_FILES})
        get_filename_component(SOURCE_PATH "${SOURCE}" PATH)
        string(REPLACE "${PROJECT_SOURCE_DIR}" "" SOURCE_PATH_REL "${SOURCE_PATH}")
        string(REPLACE "/" "\\" GROUP_PATH "${SOURCE_PATH_REL}")
        source_group("${GROUP_PATH}" FILES "${SOURCE}")
    endforeach()
endmacro()